# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM docker.m-chain.com/_BASE_NS_/mchain-baseimage:_BASE_TAG_
COPY payload/protoc-gen-go /usr/local/bin/
ADD payload/gotools.tar.bz2 /usr/local/bin/
# temporary fix for https://github.com/golang/go/issues/21373
RUN go install -a std
